### ISSUE TITLE
Missing changes

### ISSUE THREAD

**Issue by ztNFny** [Surfoo/groundspeak-api-monitoring#1]
Some recent changes on https://api.groundspeak.com/documentation are missing, e.g. "OAuth 2.0 will be required as of January 1st, 2024"

**Comment by Surfoo** [comment]
Thank you @ztNFny, this has been fixed now: https://github.com/Surfoo/groundspeak-api-monitoring/commit/e268316fb9d2d694b8571757b515da5d4d728514
